### ISSUE TITLE
Refused to display 'https://public.tableau.com...' in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by viziblydiffrnt** [cmtoomey/tableau-api#3]
When I try to use tableau-api with create-react-app I'm getting the following error: 

> Refused to display 'https://public.tableau.com/profile/mj.326#!/vizhome/NYYSeasons3/NYYSeasons?:embed=y&:display_count=yes&:embed=y&:showVizHome=n&:tabs=n&:apiID=host0' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Here's my code:

```
import React from "react";
import tableau from "tableau-api";

class TableauTest extends React.Component{
    initTableau() {
        const vizUrl = "https://public.tableau.com/profile/mj.326#!/vizhome/NYYSeasons3/NYYSeasons?:embed=y&:display_count=yes";

        const options = {
            hideTabs: true,
            width: "700px",
            height: "800px",
            onFirstInteractive: () => {
                console.log("it worked");
            }
        };
        this.viz = new window.tableau.Viz(this.container, vizUrl, options);
    }

    render() {
        return <div ref={c => (this.container=c)}
        style={{position: "absolute", left:-275, top:-375}}/>;
    }

    componentDidMount() {
        this.initTableau();
    }
}

export default TableauTest;
```

I'm then importing this into my App.js and including it like any other component. Could this just be a Tableau Public issue?

**Comment by viziblydiffrnt** [comment]
Hi Chris, 

Have you had a chance to look at this?

Thanks

**Comment by viziblydiffrnt** [comment]
Looks like it's an issue with the URL from Tableau Public. I was trying to copy and paste the URL directly from the address bar but the API expects the URL that you get from the "Share Link". In this case: 

> https://public.tableau.com/views/NYYSeasons3/NYYSeasons?:embed=y&:display_count=yes

Once I changed that it worked.

**Comment by alyssakelley** [comment]
THANK YOU SO MUCH!!!! This helped my issue today and I really appreciate you posting your update. Thank you! :D

**Comment by janglewood** [comment]
If approach with "Share link"doesn't work, try to add ```?:embed=yes``` to the link end.
