### ISSUE TITLE
Runtime error: Element is not defined

### ISSUE THREAD

**Issue by riverfour** [cmtoomey/tableau-api#4]
I created a simple test.js with just one line 
var tableau = require('tableau-api');

And then run "node test.js", but I got following error:
tableau-api\index.js:1651

global.HTMLElement = Element;
                      ^
ReferenceError: Element is not defined

Anything that I missed or misused?

Thank you,

**Comment by cmtoomey** [comment]
This package really isn't for use in Node - just browser. The Tableau JS API will require a browser to instantiate, as it is typically invoked from Tableau Server/Online (which normally serves the API code). 

https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api.htm

If you trying to do this in a node-script, it will fail.
